# Generated by Django 5.0.4 on 2026-06-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='roadmap_pdf',
            field=models.FileField(blank=True, help_text='Upload course roadmap PDF', null=True, upload_to='roadmaps/'),
        ),
    ]
