# Generated by Django 5.0.4 on 2026-06-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_duration_course_roadmap_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='roadmap_pdf',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, default='', help_text='e.g. 8 weeks (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload course syllabus or brochure PDF (max 20 MB)', null=True, upload_to='courses/pdfs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
